# Generated by Django 4.2.2 on 2023-07-05 17:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("capstone", "0002_categories_alter_user_id_sites_favorites"),
    ]

    operations = [
        migrations.AddField(
            model_name="sites",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="static"),
        ),
    ]
