# Generated by Django 4.2.3 on 2023-07-07 15:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("capstone", "0003_sites_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sites",
            name="image",
        ),
    ]
